name = "Chillambda Pack"
author = "AutiOne, pjals, xmoo"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "018057de9600d10b1241911bb8f13052da397934c864551429746f802b342b8b"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"
