name = "Chillambda Pack"
author = "AutiOne, pjals, xmoo"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "71cbf2484409a7738664c8f14bba8e752e3e43a6209d66a806309b9491fc134b"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"
